### ISSUE TITLE
SPIKE: scope effort to implement google analytics

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#137]
**TODO**
- [x] Review Blacklight documentation re: google analytics
- [ ] Review google analytics documentation
- [ ] Review google google tag manager documentation
- [ ] Attempt time bounded configuration to set up analytics against ursus-stage [timebox to 12 hours]
- [ ] Write up ticket with recommended initial pilot process

**Comment by hardyoyo** [comment]
A gem plugin for Blacklight which enables Google Analytics: https://github.com/jronallo/blacklight_google_analytics

**Comment by hardyoyo** [comment]
I'm unassigning myself, since I'm soon to be working on another project, and this research spike looks to be quite involved

**Comment by hardyoyo** [comment]
How Stanford is doing Google Analytics in SearchWorks: https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/javascripts/analytics.js

**Comment by andrewbenedictwallace** [comment]
Looking into it a bit – shouldn't stop others who want to...

**Comment by sshaferUCLA** [comment]
* I gave Andy - sourcefilter@gmail.com - edit access to Google Analytics UCLA Library Digital account
* I created property = Samvera Los Angeles Daily News Negatives UA-5600348-38
* UCLA Library web sites contain typically contain two tracking IDs.  One ID is site specific. The second ID corresponds to a general-all-sites tracking ID.  The all sites tracking ID =  UA-32672693-1

This is the UA-5600348-38 suggested tracking script which will need to have the second tracking ID - UA-32672693-1 - incorporated.  
'''
 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-5600348-38"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-5600348-38');
</script>
'''

**Comment by sshaferUCLA** [comment]
I would also like to use Google Tag Manager if possible.  This is the script for the GTM I am using:
'''

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T2SXV2"
 height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script type="text/javascript">
(function(w,d,s,l,i){

  w[l]=w[l]||[];
  w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});
  var f=d.getElementsByTagName(s)[0];
  var j=d.createElement(s);
  var dl=l!='dataLayer'?'&l='+l:'';
  j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;
  j.type='text/javascript';
  j.async=true;
  f.parentNode.insertBefore(j,f);

})(window,document,'script','dataLayer','GTM-T2SXV2');
</script>

'''

**Comment by andrewbenedictwallace** [comment]
https://github.com/jronallo/blacklight_google_analytics definitely doesn't run on current blacklight. But from the slack discussion, it looks like the nuances involve getting analytics for specific actions – hovering over this, clicking on that, &c.

For now, I think we can just drop the code above into a template to get basic page-view counts and such, while playing around more with what it offers.

**Comment by andrewbenedictwallace** [comment]
Making a next step ticket (https://github.com/UCLALibrary/ursus/issues/159) and closing this one!
